### ISSUE TITLE
Need jailbreak?

### ISSUE THREAD

**Issue by NoiseControllers** [adin283/PokemonGoControllerSuite#1]

**Comment by adin283** [comment]
Don't need to jailbreak iOS device, just install PokemonGo in AppStore.

**Comment by NoiseControllers** [comment]
but I need a mac?

**Comment by adin283** [comment]
Yes, you need a mac to run Xcode.

**Comment by NoiseControllers** [comment]
There would be a problem if I virtualized Mac machine in virtualbox?

Sorry for my english i am spanish

**Comment by adin283** [comment]
Sorry, I haven't try VM.
