### ISSUE TITLE
Can't catch pokemon

### ISSUE THREAD

**Issue by RizRiyz** [adin283/PokemonGoControllerSuite#2]
This pokemoncontroller doesnt allow user to catch pokemon.

**Comment by qfdk** [comment]
si,  i have tested yesterday. I don't think  it's a issue.
Make sure your gpx file is ok.

**Comment by adin283** [comment]
Search for some Latitude and longitude in available country, like Australia:Sydney,Melbourne.
Do not jump for a long distance, for example: from America to Australia,I guess PokemonGo server may block your account if you did this.
